-- ITOP Management System Seed Data

-- Data for table `roles`
INSERT INTO `roles` (`id`, `name`, `slug`) VALUES ('1', 'Administrator', 'admin');
INSERT INTO `roles` (`id`, `name`, `slug`) VALUES ('2', 'Instructor', 'instructor');
INSERT INTO `roles` (`id`, `name`, `slug`) VALUES ('3', 'Trainee', 'trainee');

-- Data for table `users`
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('1', '1', 'admin', NULL, NULL, NULL, NULL, 'CENTEXS Administrator', 'admin@centexs.local', '$2y$10$/UmdvyHGo04hGxRykYJSSuYJIPr/3ndLia8Do8jiiLd3cS8OLw6MG', '+6082000001', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', '747c3cc49e33b8d1c971a0184d1da742.jpeg', 'active', '2026-07-21 14:03:53', '2026-08-06 01:34:48', NULL, '2026-07-21 14:05:29', '2026-08-06 01:34:48', '2026-07-21 14:03:53', '2026-08-06 01:34:48');
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('2', '2', 'instructor', NULL, NULL, NULL, NULL, 'Instructor Aida Rahman', 'instructor@centexs.local', '$2y$10$/UmdvyHGo04hGxRykYJSSuYJIPr/3ndLia8Do8jiiLd3cS8OLw6MG', '+6082000002', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-07-21 14:03:53', '2026-08-06 01:41:47', NULL, '2026-07-23 14:50:13', '2026-08-06 01:41:47', '2026-07-21 14:03:53', '2026-08-06 01:41:47');
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('3', '3', 'trainee', NULL, NULL, NULL, NULL, 'calvin', 'trainee@centexs.local', '$2y$10$/UmdvyHGo04hGxRykYJSSuYJIPr/3ndLia8Do8jiiLd3cS8OLw6MG', '', '', '1', NULL, '1', '7', '', 'Male', NULL, '', 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-07-21 14:03:53', '2026-08-06 01:34:15', NULL, '2026-07-21 14:57:07', '2026-08-06 01:34:15', '2026-07-21 14:03:53', '2026-08-06 01:34:15');
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('4', '3', NULL, NULL, NULL, NULL, NULL, 'Ahmad Bin Abdullah', 'dummy_trainee_1@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100000', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', '2026-08-05 14:05:48', NULL, '2026-08-05 14:05:48', '2026-08-05 14:05:48', '2026-08-05 09:48:45', '2026-08-05 14:05:48');
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('5', '3', NULL, NULL, NULL, NULL, NULL, 'Siti Binti Sulaiman', 'dummy_trainee_2@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100001', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', '2026-08-05 13:59:42', NULL, '2026-08-05 13:59:42', '2026-08-05 13:59:42', '2026-08-05 09:48:45', '2026-08-05 13:59:42');
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('6', '3', NULL, NULL, NULL, NULL, NULL, 'John Smith', 'dummy_trainee_3@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100002', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('7', '3', NULL, NULL, NULL, NULL, NULL, 'Jane Doe', 'dummy_trainee_4@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100003', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('8', '3', NULL, NULL, NULL, NULL, NULL, 'Ali Bin Mutalib', 'dummy_trainee_5@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100004', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('9', '3', NULL, NULL, NULL, NULL, NULL, 'Fatima Binti Hassan', 'dummy_trainee_6@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100005', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('10', '3', NULL, NULL, NULL, NULL, NULL, 'Michael Johnson', 'dummy_trainee_7@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100006', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('11', '3', NULL, NULL, NULL, NULL, NULL, 'Sarah Brown', 'dummy_trainee_8@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100007', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('12', '3', NULL, NULL, NULL, NULL, NULL, 'David Williams', 'dummy_trainee_9@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100008', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('13', '3', NULL, NULL, NULL, NULL, NULL, 'Emma Jones', 'dummy_trainee_10@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100009', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('14', '3', NULL, NULL, NULL, NULL, NULL, 'Daniel Garcia', 'dummy_trainee_11@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100010', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('15', '3', NULL, NULL, NULL, NULL, NULL, 'Olivia Miller', 'dummy_trainee_12@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100011', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('16', '3', NULL, NULL, NULL, NULL, NULL, 'James Davis', 'dummy_trainee_13@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100012', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('17', '3', NULL, NULL, NULL, NULL, NULL, 'Grace Rodriguez', 'dummy_trainee_14@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100013', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('18', '3', NULL, NULL, NULL, NULL, NULL, 'William Martinez', 'dummy_trainee_15@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100014', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('19', '3', NULL, NULL, NULL, NULL, NULL, 'Sophia Hernandez', 'dummy_trainee_16@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100015', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('20', '3', NULL, NULL, NULL, NULL, NULL, 'Benjamin Lopez', 'dummy_trainee_17@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100016', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('21', '3', NULL, NULL, NULL, NULL, NULL, 'Chloe Gonzalez', 'dummy_trainee_18@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100017', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('22', '3', NULL, NULL, NULL, NULL, NULL, 'Lucas Wilson', 'dummy_trainee_19@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100018', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('23', '3', NULL, NULL, NULL, NULL, NULL, 'Mia Anderson', 'dummy_trainee_20@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100019', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('24', '3', NULL, NULL, NULL, NULL, NULL, 'Henry Thomas', 'dummy_trainee_21@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100020', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('25', '3', NULL, NULL, NULL, NULL, NULL, 'Lily Taylor', 'dummy_trainee_22@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100021', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('26', '3', NULL, NULL, NULL, NULL, NULL, 'Alexander Moore', 'dummy_trainee_23@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100022', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('27', '3', NULL, NULL, NULL, NULL, NULL, 'Zoey Jackson', 'dummy_trainee_24@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100023', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('28', '3', NULL, NULL, NULL, NULL, NULL, 'Matthew Martin', 'dummy_trainee_25@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100024', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('29', '3', NULL, NULL, NULL, NULL, NULL, 'Avery Lee', 'dummy_trainee_26@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100025', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('30', '3', NULL, NULL, NULL, NULL, NULL, 'Joseph Perez', 'dummy_trainee_27@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100026', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('31', '3', NULL, NULL, NULL, NULL, NULL, 'Evelyn Thompson', 'dummy_trainee_28@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100027', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('32', '3', NULL, NULL, NULL, NULL, NULL, 'Samuel White', 'dummy_trainee_29@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100028', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('33', '3', NULL, NULL, NULL, NULL, NULL, 'Ella Harris', 'dummy_trainee_30@example.com', '$2y$10$Z6nSPEwcQfbjOokb/JNuZutK5siG3cQzhyxlWMJCGT72CZ8.I3We.', NULL, NULL, NULL, NULL, NULL, NULL, 'ID100029', NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', '2026-08-05 09:48:45', NULL, NULL, NULL, NULL, '2026-08-05 09:48:45', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('34', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 1', 'mocktrainee1@example.com', '$2y$10$0kGYwvW.dk8ycqJIcmQqBOTYHENRccjt7ydMGkonxA2.FMJaLtEU2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-18 23:34:30', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('35', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 2', 'mocktrainee2@example.com', '$2y$10$0kGYwvW.dk8ycqJIcmQqBOTYHENRccjt7ydMGkonxA2.FMJaLtEU2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-22 23:34:30', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('36', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 3', 'mocktrainee3@example.com', '$2y$10$0kGYwvW.dk8ycqJIcmQqBOTYHENRccjt7ydMGkonxA2.FMJaLtEU2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-23 23:34:30', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('37', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 4', 'mocktrainee4@example.com', '$2y$10$45dCF078XIrnV7FR/HSXZe6Hp3IgVMrV/2kVfZM2vZiIffIdFW.hS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-07 23:34:53', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('38', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 5', 'mocktrainee5@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-26 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('39', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 6', 'mocktrainee6@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-11 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('40', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 7', 'mocktrainee7@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-19 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('41', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 8', 'mocktrainee8@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-17 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('42', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 9', 'mocktrainee9@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-02 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('43', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 10', 'mocktrainee10@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-13 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('44', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 11', 'mocktrainee11@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-20 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('45', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 12', 'mocktrainee12@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-21 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('46', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 13', 'mocktrainee13@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-30 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('47', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 14', 'mocktrainee14@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-15 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('48', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 15', 'mocktrainee15@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-09 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('49', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 16', 'mocktrainee16@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-18 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('50', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 17', 'mocktrainee17@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-08-01 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('51', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 18', 'mocktrainee18@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-15 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('52', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 19', 'mocktrainee19@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-22 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('53', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 20', 'mocktrainee20@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-31 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('54', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 21', 'mocktrainee21@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-24 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('55', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 22', 'mocktrainee22@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-20 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('56', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 23', 'mocktrainee23@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-13 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('57', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 24', 'mocktrainee24@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-03 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('58', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 25', 'mocktrainee25@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-10 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('59', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 26', 'mocktrainee26@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-26 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('60', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 27', 'mocktrainee27@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-11 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('61', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 28', 'mocktrainee28@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-21 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('62', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 29', 'mocktrainee29@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-29 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('63', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 30', 'mocktrainee30@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-08 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('64', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 31', 'mocktrainee31@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-25 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('65', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 32', 'mocktrainee32@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-10 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('66', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 33', 'mocktrainee33@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-25 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('67', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 34', 'mocktrainee34@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-08 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('68', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 35', 'mocktrainee35@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-19 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('69', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 36', 'mocktrainee36@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-25 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('70', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 37', 'mocktrainee37@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-22 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('71', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 38', 'mocktrainee38@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-28 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('72', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 39', 'mocktrainee39@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-07-07 23:35:11', NULL);
INSERT INTO `users` (`id`, `role_id`, `role`, `position`, `department`, `office_location`, `employee_id`, `name`, `email`, `password_hash`, `phone`, `address`, `company_id`, `institution_id`, `location_id`, `profession_id`, `identity_number`, `gender`, `date_of_birth`, `institution_company`, `time_zone`, `theme_preference`, `default_landing_page`, `notification_preferences`, `two_factor_enabled`, `profile_picture`, `status`, `email_verified_at`, `last_login`, `password_changed_at`, `first_login`, `last_active`, `created_at`, `updated_at`) VALUES ('73', '3', NULL, NULL, NULL, NULL, NULL, 'Mock Trainee 40', 'mocktrainee40@example.com', '$2y$10$v56ZOrusCjSU2vRHNjOJiuhp51omojNMNw5INk/cIFbZ0UDk8H3F2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Asia/Kuala_Lumpur', 'light', 'dashboard', NULL, '0', NULL, 'active', NULL, NULL, NULL, NULL, NULL, '2026-06-22 23:35:11', NULL);

-- Data for table `academies`
INSERT INTO `academies` (`id`, `code`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('1', 'ADGEA', 'Aerospace, Digital & Green Energy Academy', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `academies` (`id`, `code`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('2', 'IESGA', 'Industry & ESG Academy', NULL, 'active', '2026-08-05 11:39:55', NULL);

-- Data for table `training_categories`
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('1', 'Telecommunication', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('2', 'Digital Technology', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('3', 'Green Energy', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('4', 'Internet of Things (IoT)', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('5', 'Industry 4.0', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('6', 'Hospitality', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('7', 'ESG', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('8', 'Electrical', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('9', 'Manufacturing', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('10', 'AI & Education', NULL, 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `training_categories` (`id`, `name`, `description`, `status`, `created_at`, `updated_at`) VALUES ('11', 'Security', NULL, 'active', '2026-07-21 14:04:23', NULL);

-- Data for table `locations`
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('1', 'Kuching', 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('2', 'Bintulu', 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('3', 'Lawas', 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('4', 'Kota Samarahan', 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('5', 'Kapit', 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('6', 'Sabah', 'active', '2026-07-21 14:04:23', NULL);
INSERT INTO `locations` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('7', 'Brunei', 'active', '2026-07-21 14:04:23', NULL);

-- Data for table `professions`
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('1', 'Director', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('2', 'Managing Director', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('3', 'Project Manager', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('4', 'Technical Director', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('5', 'Manager', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('6', 'Engineer', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('7', 'Assistant Engineer', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('8', 'Technician/Linesman', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('9', 'Wireman', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('10', 'Supervisor', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('11', 'Professor/Lecturer', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('12', 'Pensyarah TVET', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('13', 'Pegawai Latihan Vokasional', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('14', 'Procurement', 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `professions` (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES ('15', 'Executive', 'active', '2026-08-05 11:39:55', NULL);

-- Data for table `companies`
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('1', 'Jalur Milenium', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('2', 'Lyskcom Tec Sdn Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('3', 'TelBru (Brunei)', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('4', 'MTSB', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('5', 'Silverridge Holdings Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('6', 'Universiti Teknologi MARA', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('7', 'Sacofa', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('8', 'H.M.M Enterprise', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('9', 'Sarawak Energy', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('10', 'PNR Engineering Sdn Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('11', 'Valsa', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('12', 'Ikhwan Electrical Works Enterprise', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('13', 'BSC Resources Sdn Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('14', 'Bizwin Technologies', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('15', 'Sea Telco Engineering Sdn. Bhd.', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('16', 'WG Utama', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('17', 'SM Digital Innovation', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('18', 'AM-ME Sdn Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('19', 'Foursons Sdn. Bhd.', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('20', 'Sarawak Petchem', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('21', 'TVETMARA Bintulu', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('22', 'An-Nash Resources', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('23', 'PETROS', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('24', 'Maxglow', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('25', 'Petronas', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('26', 'OM Holding Ltd.', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('27', 'Lim Aik Chai Electrical Sdn Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);
INSERT INTO `companies` (`id`, `name`, `location_id`, `status`, `created_at`, `updated_at`) VALUES ('28', 'Metro Glide Sdn Bhd', NULL, 'active', '2026-08-05 11:39:55', NULL);

-- Data for table `website_settings`
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('1', 'site_name', 'CENTEXS ITOP Management System');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('2', 'support_email', 'info@centexs.my');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('3', 'hero_title', 'CENTEXS training operations in one secure web platform');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('4', 'hero_subtitle', 'Manage programme registration, learning materials, assessments, progress, reports, evaluations, and certificates for real-world ITOP delivery.');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('5', 'footer_about', 'Centre for Technology Excellence Sarawak (CENTEXS) is a premier training institution in Sarawak, delivering industry-driven technical and vocational programmes.');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('6', 'footer_address', 'CENTEXS Kuching, Jalan Canna, Off Jalan Wan Alwi, 93350 Kuching, Sarawak, Malaysia');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('7', 'footer_phone', '+60 82-363 200');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('8', 'footer_email', 'info@centexs.my');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('9', 'footer_social_facebook', 'https://www.facebook.com/centexs.sarawak');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('10', 'footer_social_linkedin', 'https://www.linkedin.com/company/centexs');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('11', 'show_upcoming_intakes', '1');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('12', 'show_success_stories', '1');
INSERT INTO `website_settings` (`id`, `setting_key`, `setting_value`) VALUES ('13', 'show_announcements_home', '1');

